### ISSUE TITLE
Any plans to support other online libraries/archives? 

### ISSUE THREAD

**Issue by stereobooster** [paperscape/paperscape-data#1]
https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.Free_copies_of_some_articles
https://openaccessbutton.org/

**Comment by dpgeorge** [comment]
@stereobooster thanks for the links to those article repositories.

Unfortunately, right now the Paperscape developers don't have the resources to do much more than basic maintenance of this project.
