### ISSUE TITLE
Update of the data?

### ISSUE THREAD

**Issue by klausondrag** [paperscape/paperscape-data#2]
Hi, the website paperscape.org currently states "Last updated: 15 March 2018", the same date as this issue was created. This means you still update your database. Are there plans to update this repository regularly as well? I could help you if you want. :slightly_smiling_face:

**Comment by dpgeorge** [comment]
I don't see any reason not to update the data, even if we just add it once a year (2016 and 2017 could be added).  @rknegjens do you have a script lying around to create the archive files?

**Comment by rknegjens** [comment]
Yes we can add 2016 and 2017, will let you know when it's done.

**Comment by rknegjens** [comment]
Done!

**Comment by klausondrag** [comment]
Thanks!

**Comment by dpgeorge** [comment]
Thanks @rknegjens!
