### ISSUE TITLE
citation data seems off

### ISSUE THREAD

**Issue by simon-dedeo** [paperscape/paperscape-data#3]
I'm playing around with your dataset (thank you!)

I'm finding some inconsistencies with the data I can access through ADS. For example, this is an entry in pscp-1991:

hep-th/9108001;hep-th;0;0;;J.H.Horne,G.T.Horowitz;Exact Black String Solutions in Three Dimensions

i.e., "hep-th/9108001" has zero citations. However, I find it has at least 175 citations (!)

For example, below is a list that I can pull from the ADS API. At the very least, https://arxiv.org/abs/1108.2700 should have been picked up!

Do you guys have any sense of what might have happened? You can also reach me at sdedeo[at]andrew.cmu.edu

Simon

"2018PhLB..777..361D", "2017JHEP...10..212D", "2015EPJC...75..227H", "2017arXiv170707445V", "2016arXiv160105749G", "2014arXiv1412.5618G", "2008arXiv0806.1018D", "2003hep.th....5254N", "2002hep.th....2147K", "1999gr.qc.....2047H", "1998hep.th....9015B", "1994hep.th....6136K", "1992hep.th....9068K", "2017PhLB..772..791E", "2017PhLB..773..440H", "2017EPJC...77..647H", "2016EPJC...76..296H", "2015EPJC...75..131L", "2014JHEP...06..002H", "2014IJTP...53.3794S", "2014EL....10750001D", "2014BrJPh..44..832N", "2013PhRvL.110y1102E", "2013JPSJ...82f4006S", "2012IJMPD..2150049M", "2010PhRvD..82f4040H", "2010IJTP...49..445S", "2009IJTP...48..248Y", "2008PhRvD..78d4010D", "2008PhRvD..78f4031D", "2008PhLB..659..476D", "2008JHEP...05..060D", "2007PhRvD..75d6008A", "2007PhRvD..75d4020S", "2007PhRvD..75h4013D", "2007JHEP...12..020B", "2007JHEP...11..045D", "2007JHEP...01..071G", "2007ForPh..55..161O", "2006PhRvD..73j4013D", "2006PhLB..638..515M", "2006PhDT.......155D", "2006PhDT........53O", "2006NuPhB.744..136B", "2006MPLA...21.1737M", "2005PhLB..624..297M", "2005NuPhB.719....3G", "2005NuPhB.714..179G", "2005JHEP...05..028G", "2005JHEP...07..072D"...

**Comment by rknegjens** [comment]
Hi Simon,

The paperscape dataset gives matched arXiv *references* (papers a paper refers to), not citations (papers that refer to a paper). Because this is a paper from close to the start of the arXiv, it makes sense we didn't match any arXiv references.

From the reference data you should be able to build a citation graph.

FYI we find 145 citations for hep-th/9108001, some of which may be non-arXiv (we also have some extra paper records).

**Comment by simon-dedeo** [comment]
Thank you. I am a moron :)
