### ISSUE TITLE
Document data generation?

### ISSUE THREAD

**Issue by a3nm** [paperscape/paperscape-data#4]
Hi,

I was interested to find the code that you use to process the arXiv dump and extract the citation information provided in this repository, but I couldn't find it. Could you consider adding a note to the README to point out how the data was generated?

Thanks for this interesting project!

**Comment by dpgeorge** [comment]
Thanks for your interest.  Unfortunately we haven't made public the code that extracts the citation data.  And, since it's a lot of work for us to do this, it's unlikely we will have time to make it public.  Sorry about that!

**Comment by a3nm** [comment]
OK, no worries!
